### ISSUE TITLE
Documentation refers to `safetimers`

### ISSUE THREAD

**Issue by stelcheck** [Wizcorp/safe-timers#3]
```javascript
const setTimeout = require('safe-timers').setTimeout;
```

This should be `safe-timers` instead.

**Comment by ronkorving** [comment]
Where is that? I'm not sure I follow.
The only `safetimers` I see are variable names (which can't contain `-`).

**Comment by stelcheck** [comment]
https://www.npmjs.com/package/safe-timers

**Comment by ronkorving** [comment]
ie: you're really suggesting to do a release for docs updates? :)

**Comment by stelcheck** [comment]
I had not realized this was just not released.

This being said, yes, I would suggest that perhaps... so to avoid confusion.
