### ISSUE TITLE
Suggestion: API parity with clearTimeout and clearInterval

### ISSUE THREAD

**Issue by JamesMGreene** [Wizcorp/safe-timers#4]
What are your thoughts on completing API parity with the core Timers APIs by adding the top-level methods `clearTimeout` and `clearInterval` to this module's API?

Obviously it would be simple to do so:

```js
exports.clearTimeout = function (timer) {
	if (timer instanceof Timeout) {
		timer.clear();
	}
};

exports.clearInterval = function (timer) {
	if (timer instanceof Interval) {
		timer.clear();
	}
};
```

Happy to submit a PR for this, plus unit tests, if you're good with the suggestion.

**Comment by JamesMGreene** [comment]
I'd also really like to see these added as I am going to recommend that known consumers of my older module `safetimeout` (basically the same intent as your module) switch over to `safe-timers`.

**Comment by JamesMGreene** [comment]
@ronkorving: Thoughts on this one?

**Comment by ronkorving** [comment]
Sure, sounds good 👍 
I think you don't even really need the if-statements by the way.

This also works in the browser:

```js
var t = setTimeout(function () { console.log('fired'); }, 10);
clearInterval(t);
```

`t` does not fire.

**Comment by JamesMGreene** [comment]
@ronkorving: Well, the browser's behavior is really just am implementation shortcut they chose to take rather than a guaranteed behavior.  However, regardless, if you are suggesting to keep this module's implementation similarly loose (which it seems like you are), then I'm fine with that.
